dna = "GTAGTGTTCCGGCCACACGCCGCTAAGAGGGAAGTCACCAGGAGCTTATGACTATACATTTAGAGCGTATTGCTGGACCTACCAGAGAAAAAGCACTATTAATCTCTTTTACAGTCCCATCTGGATCTCCCGGCCTTCGCGCCCGTGGTAAGTTCGGATGAATTGAGTTCACTATGCCAGCATCTGACGCACGGTGAGGGATAGGTGTTGTACGACGACTTTCATATCCTCGCCATACGGGAGACACGTACGCACAGCGCGAGTGCTTAGCCCAAGAAAATATTTATAACGGCGTTGCGCTGGTACTTCTCTCGAAGTGTGCGGGTCGAGTGATACCCCTTTGAGCGCCTGAAAACTCGACAGGGCCGAAGGTTCACCCCTGGCTTAACTTTTAGTTAAGATAGAAAGCATCTTCATTCCTCTAGTATATACTGGATACCTTATGAAGGGCGAGGTCGCCCCAAGTAGTAAAAGCTAGCGCATATACAACGACCGTACTCCATGAGTTTCTTAGGTAACAAAAGCCTAGTTCACCAGAGCAGAGGGCTCGAATATAACCGGACGGAGGTGCACCCTCGTTGTACGACTTAACCGTGAGTGGCTTCATAGTTCGTCACAAGAATTATCGTATGGTCGCCCACTCCCTTCTGCTCTACTTAATTATTGCGCTAGGTCTTTTCGGTATGTAAATGCCAAGGCTTAGCTAACGTACCTCTAACTTTCGACCGTGTGGGAGCTTCTTTCCGTTAGAGAACGAACTACTTGATTATAATTGGCAGCTGTCCATAGCTTGTATCCGCGTC"

dna = dna[::-1] #reverses the dna strand
complement = ""

for i in dna:
    if i == "A":
        complement += "T"
    if i == "T":
        complement += "A"
    if i == "G":
        complement += "C"
    if i == "C":
        complement += "G"

print(complement)