#DNA that was given
dna = "GAATGATAAGAAACGATCACCTTTGTAAACCGCTTAATCGCGACTATATCCAGTCTCTTTTAGGAAATAGACTTATAGTCGACCTAAGAGGGACTCGTCCTGGTAGTAGGCATTAGCTCTGGCGATAAAGCGTTAACAATGTAAGACCAAAGAAGCGACCTGCATCCTAGCTATGTTCGCAGAGCTCCGGGGCACCTTGCCCAAGTGTCAGGAGCAGGCGTGCCGCAAGTACATCGGAGTCGGTATGTGTTTCATTTTCCGACCTAACTTTCTTTCTAGGCACTTTTCCCCGGTTTACCCATCATGGACGACTTTATTACCGCGTTTAAGGCCTTCTCTTTGTTAAAGTGCTCCCTAGCGATGGGTTACGTGGAGACTCTTACGGACATCCAGCGATAGTTCTCTCAAAGGGGTAGGGTACCTCAGGTGGCCATGCTGGATGCTGCCAGGTCGCCTCTTCCGTTATATACATCATCCTCCTAAAGCCGTTACTGAGAGAAAGGTTTGGGTAATGACTTGCACCAATCGATTCATGTATGCTACTTAGCCCGGTGGCAGTTCGACCGGGCTCCAACCCGGTGTAGTTTTCGCAAATTCTGACTCATGCGGGGTTCTGTGTTGTCTCCTGTACCTCCTGTGCTCGGACACGCCTGAAGACTGAAATGCTTGGAAAAGTGTGTTGGTGAGATCACAACTCCCACTTTGCTACGGTTTAATCCGAAACCCGTAATCCAGTATCAGAACCAAAGGGAACACAAACATCATAAGCCCTTAGGCGAAAGTCTGAGATTCTCTTCGGTATCCTCTCGGTCATAGGCAAGCTAAAACTTTTTTTACCGAATCGGATGCTGATCGGTAGAGAGTGGAATAGTGGCAGCGACGGTAGGCCAGTGTCGATCGGTGATTTACCGCTATGTTTG"

#solution 1: Using the replace method to do the problem quickly
rna = dna.replace("T", "U")

print(rna)

#solution 2: Using a for loop to add each character and switch if it's a T
rna = ""

for i in dna:
    if i == "T":
        rna += "U"
    else:
        rna += i

print(rna)